ignore: |
  rendered/

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    spaces: consistent
    indent-sequences: consistent
  line-length:
    max: 240
    level: warning
    allow-non-breakable-inline-mappings: true
  trailing-spaces:
    level: warning
  new-line-at-end-of-file:
    level: warning
  truthy: disable
