name: Pre-Commit

on:
  workflow_call:

jobs:
  precommit:
    name: Pre Commit Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pre-commit/action@v3.0.0
