name: Run create and rollback release test

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/create-release.yml"
      - ".github/workflows/rollback-release.yml"

jobs:
  create-prerelease:
    uses: ./.github/workflows/create-release.yml
    secrets: inherit
    with:
      is_draft: false
      is_prerelease: true

  rollback-prerelease:
    uses: ./.github/workflows/rollback-release.yml
    needs: create-prerelease
    secrets: inherit
    with:
      version: ${{ needs.create-prerelease.outputs.version }}

  create-release:
    uses: ./.github/workflows/create-release.yml
    secrets: inherit
    with:
      is_draft: false
      is_prerelease: false

  rollback-release:
    uses: ./.github/workflows/rollback-release.yml
    needs: create-release
    secrets: inherit
    with:
      version: ${{ needs.create-release.outputs.version }}
